### ISSUE TITLE
Doesn't work with Node v6.11

### ISSUE THREAD

**Issue by oransel** [diversario/node-ssdp#82] opened 2017-07-11 02:51 UTC
The client example quits without any errors.

**Comment by oransel** [comment] 2017-07-11 21:20
this makes it work.

```
SSDP.prototype._createSockets = function () {
  var interfaces = os.networkInterfaces()
    , self = this

  this.sockets = {}

  Object.keys(interfaces).forEach(function (iName) {
    self._logger('discovering all IPs from interface %s', iName)

    interfaces[iName].forEach(function (ipInfo) {
      if (ipInfo.internal == false && ipInfo.family == "IPv4") {
        self._logger('Will use interface %s', iName)
        self.sockets[ipInfo.address] = dgram.createSocket('udp4');
      }
    })
  })
}
```

**Comment by diversario** [comment] 2017-09-26 16:06
I cannot reproduce this, so I'll close it.

**Closed by diversario** 2017-09-26 16:06 UTC
Labels: invalid
