### ISSUE TITLE
Client not detecting my Panasonic Viera TV

### ISSUE THREAD

**Issue by soloam** [diversario/node-ssdp#95] opened 2018-08-10 09:24 UTC
Hello I have a Panasonic Viera VT60, and I would like to cast movies to the youtube app of the TV. I can with no problem cast movies from the youtube app from my mobile, but when I run your client example I can't detect my tv. I was redirected here because I'm using a packages that includes this library ([nodecast](https://github.com/contra/nodecast)), and when I opened a issue in the package, the developer told me that it uses this library, and that you might be able to help me understand if this is a problem on my side, the library or if simply this is not designed to my use case scenario. 

I also have a kodi device running with [TubeCast](https://kodi.tv/addon/scripts/tubecast) and it also works great with my youtube app on my mobile, but it's not detected in your library.

Thank you

**Comment by soloam** [comment] 2018-09-06 14:36
It works now, I can only find when I use the timer, if I do only a search it stops before finding anything, If I set a timer it starts finding.

Thank You

**Comment by contra** [comment] 2018-09-06 17:14
Hmm, it seems like the issue might be that search doesn't keep the process open so it ends before getting a response. I'm having the same issue right now.

**Comment by soloam** [comment] 2018-09-06 17:19
I solved it by adding to the end

`setTimeout(function() {},5000)`

Now I can get results

**Comment by diversario** [comment] 2018-09-07 02:11
Right, so, node process will exit if there's nothing keeping it up; that's why in the example there's a `setTimeout` bit, to keep it running.

**Comment by diversario** [comment] 2018-09-07 02:15
@soloam is this a non-issue, then? Can we close this?

**Comment by contra** [comment] 2018-09-07 15:47
@diversario The issue is that node-ssdp should keep it open until the Client is closed, you shouldn't have to manually ref the process via setinterval noops.

**Comment by mroch** [comment] 2019-03-30 21:40
removing the `socket.unref()` in `SSDP.prototype._createSockets` also fixes this issue. it'll stay listening until you close the sockets by calling `client.stop()`.

**Closed** 2022-01-20 12:21 UTC
